"""add longitude and latitude to the hospital model

Revision ID: b19a85d79f73
Revises: dd9e2a5276cc
Create Date: 2025-03-19 05:29:25.037295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19a85d79f73'
down_revision: Union[str, None] = 'dd9e2a5276cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('hospitals', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'long')
    op.drop_column('hospitals', 'lat')
    # ### end Alembic commands ###
