"""add blood_type, quantity, and accepted_user_id Columns

Revision ID: 7511cc44e504
Revises: b15517fc7af4
Create Date: 2025-03-10 15:43:12.489211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7511cc44e504'
down_revision: Union[str, None] = 'b15517fc7af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('blood_type', sa.String(length=20), nullable=False))
    op.add_column('requests', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('requests', sa.Column('accepted_user_id', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'accepted_user_id')
    op.drop_column('requests', 'quantity')
    op.drop_column('requests', 'blood_type')
    # ### end Alembic commands ###
