"""initial migration

Revision ID: b15517fc7af4
Revises: 
Create Date: 2025-03-06 14:30:18.921156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15517fc7af4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('request_type', sa.String(length=15), nullable=False),
    sa.Column('request_status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
