"""add long and lat column to the request model

Revision ID: cc92c1616554
Revises: 7511cc44e504
Create Date: 2025-03-19 21:56:31.991444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc92c1616554'
down_revision: Union[str, None] = '7511cc44e504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('long', sa.Float(), nullable=False))
    op.add_column('requests', sa.Column('lat', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'lat')
    op.drop_column('requests', 'long')
    # ### end Alembic commands ###
