"""remove the long and lat later to be added

Revision ID: 3390d3416379
Revises: 02f7124dbbe6
Create Date: 2025-03-15 05:07:06.891479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3390d3416379'
down_revision: Union[str, None] = '02f7124dbbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'long')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('long', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
