"""add lat and long after I removed it to reflect floating point numbers instead of int

Revision ID: 54488cd18f92
Revises: 3390d3416379
Create Date: 2025-03-15 05:08:16.547975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54488cd18f92'
down_revision: Union[str, None] = '3390d3416379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'long')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###
